/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ShikariX
 */
public class Second_Java extends javax.swing.JFrame {

    /**
     * Creates new form Second_Java
     */
    public Second_Java() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel13 = new javax.swing.JPanel();
        rb45 = new javax.swing.JRadioButton();
        rb46 = new javax.swing.JRadioButton();
        buttonGroup3 = new javax.swing.ButtonGroup();
        L24 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        chb21 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tf24 = new javax.swing.JTextField();
        tf25 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        chb22 = new javax.swing.JCheckBox();
        tf26 = new javax.swing.JTextField();
        tf27 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf29 = new javax.swing.JTextField();
        tf28 = new javax.swing.JTextField();
        rb22 = new javax.swing.JRadioButton();
        rb21 = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tf210 = new javax.swing.JTextField();
        tf211 = new javax.swing.JTextField();
        chb24 = new javax.swing.JCheckBox();
        jPanel9 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        chb25 = new javax.swing.JCheckBox();
        tf212 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        rb23 = new javax.swing.JRadioButton();
        rb24 = new javax.swing.JRadioButton();
        cb21 = new javax.swing.JComboBox<>();
        b22 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        rb26 = new javax.swing.JRadioButton();
        rb25 = new javax.swing.JRadioButton();
        P21 = new javax.swing.JPanel();
        cb22 = new javax.swing.JComboBox<>();
        L21 = new javax.swing.JLabel();
        cb23 = new javax.swing.JComboBox<>();
        L22 = new javax.swing.JLabel();
        L23 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tf21 = new javax.swing.JTextField();
        tf22 = new javax.swing.JTextField();
        tf23 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 111, Short.MAX_VALUE)
        );

        jLabel6.setText("jLabel4");

        jCheckBox2.setText("Take according to IS800 table 5 (cl. 5.4.1)");

        jLabel5.setText("Governed by ultimate strength (ymf)");

        jLabel8.setText("Governed by yielding (ym0)");

        jTextField6.setText("jTextField4");

        jTextField7.setText("jTextField5");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        rb45.setText("Design for economical section");

        rb46.setText("Design for particular section");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb46)
                    .addComponent(rb45))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rb45)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb46)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        L24.setFont(new java.awt.Font("Ubuntu Mono", 1, 26)); // NOI18N
        L24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(L24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1050, 60));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Properties of Steel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        chb21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chb21.setText("Fe410 Steel");
        chb21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb21ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Ultimate Tensile Stress in Mpa");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Yield Stress in MPa");

        tf24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf24ActionPerformed(evt);
            }
        });

        tf25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf25ActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Partial Safety Factors", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Governed by ultimate strength (ym1)");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Governed by yielding (ym0)");

        chb22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chb22.setText("Take according to IS800 table 5 (cl. 5.4.1)");
        chb22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb22ActionPerformed(evt);
            }
        });

        tf26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf26ActionPerformed(evt);
            }
        });

        tf27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf27ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf26)
                            .addComponent(tf27)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(chb22)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chb22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chb21)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf25, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf24, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chb21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Properties Of Bolts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Ultimate tensile strength in MPa");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Diameter of bolt in mm");

        tf29.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf29ActionPerformed(evt);
            }
        });

        tf28.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf28ActionPerformed(evt);
            }
        });

        buttonGroup2.add(rb22);
        rb22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rb22.setText("Grade 8.8");
        rb22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb22ActionPerformed(evt);
            }
        });

        buttonGroup2.add(rb21);
        rb21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rb21.setText("Grade 4.6");
        rb21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb21ActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pitch and End Distance", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Pitch in mm");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("End Distance in mm");

        tf210.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        tf211.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf211.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf211ActionPerformed(evt);
            }
        });

        chb24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chb24.setText("Take min. value according to IS800 ");
        chb24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb24ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf210, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(chb24)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf211, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chb24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf210, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf211, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Partial Safety Factor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Custom safety factor (ymf)");

        chb25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chb25.setText("Take according to IS800 table 5 (cl. 5.4.1)");
        chb25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb25ActionPerformed(evt);
            }
        });

        tf212.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(chb25)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                        .addComponent(tf212, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(chb25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(tf212, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tf29, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(rb21))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rb22)
                                    .addComponent(tf28, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(24, 24, 24)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb22)
                    .addComponent(rb21))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tf28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Type Of Section", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        buttonGroup1.add(rb23);
        rb23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rb23.setText("Equal");
        rb23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb23ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb24);
        rb24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rb24.setText("Unequal");
        rb24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb24ActionPerformed(evt);
            }
        });

        cb21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cb21.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Outstanding Leg Larger", "Connected Leg Larger" }));
        cb21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb21ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(rb24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                        .addComponent(cb21, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(rb23)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rb23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb24)
                    .addComponent(cb21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 580, -1, -1));

        b22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/baclkk.jpg"))); // NOI18N
        b22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b22ActionPerformed(evt);
            }
        });
        getContentPane().add(b22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 750, 120, 110));

        b3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/oitt.jpg"))); // NOI18N
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 750, 240, 110));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Type of Design", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        buttonGroup3.add(rb26);
        rb26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rb26.setText("Check for a particular section");
        rb26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb26ActionPerformed(evt);
            }
        });

        buttonGroup3.add(rb25);
        rb25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rb25.setText("Design for economical section");
        rb25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb25ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb25)
                    .addComponent(rb26))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rb25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb26)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, -1, -1));

        P21.setBackground(new java.awt.Color(255, 255, 255));
        P21.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Choose ISA Section", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        P21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        cb22.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        cb22.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "20X20X3", "25X25X3", "20X20X4", "30X30X3", "25X25X4", "35X35X3", "25X25X5", "30X30X4", "40X40X3", "45X45X3", "35X35X4", "30X30X5", "50X50X3", "40X40X4", "35X35X5", "45X45X4", "40X40X5", "35X35X6", "50X50X4", "45X45X5", "40X40X6", "50X50X5", "45X45X6", "55X55X5", "50X50X6", "60X60X5", "65X65X5", "55X55X6", "70X70X5", "60X60X6", "75X75X5", "65X65X6", "70X70X6", "55X55X8", "75X75X6", "60X60X8", "80X80X6", "65X65X8", "55X55X10", "90X90X6", "70X70X8", "60X60X10", "75X75X8", "100X100X6", "65X65X10", "80X80X8", "70X70X10", "90X90X8", "75X75X10", "80X80X10", "100X100X8", "110X110X8", "90X90X10", "80X80X12", "100X100X10", "90X90X12", "130X130X8", "110X110X10", "100X100X12", "110X110X12", "130X130X10", "150X150X10", "130X130X12", "110X110X15", "150X150X12", "130X130X15", "150X150X15", "200X200X12", "150X150X18", "200X200X15", "200X200X18", "200x200X25" }));
        cb22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb22ActionPerformed(evt);
            }
        });

        L21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        L21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        cb23.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        cb23.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "30X20X3", "30X20X4", "40X25X3", "45X30X3", "30X20X5", "50X30X3", "40X25X4", "45X30X4", "40X25X5", "50X30X4", "45X30X5", "40X25X6", "50X30X5", "45X30X6", "50X30X6", "60X40X5", "65X45X5", "7045X5", "60X40X6", "75X50X5", "65X45X6", "80X50X5", "70X45X6", "75X50X6", "60X40X8", "80X50X6", "65X45X8", "70X45X8", "90X60X6", "75X50X8", "100X65X6", "80X50X8", "100X75X6", "70X45X10", "90X60X8", "75X50X10", "125X75X6", "80X50X10", "100X65X8", "125X95X6", "100X75X8", "90X60X10", "125X75X8", "100X65X10", "100X75X10", "90X60X12", "125X95X8", "150X75X8", "125X75X10", "100X75X12", "150X115X8", "125X95X10", "150X75X10", "125X95X12", "150X115X10", "150X75X12", "200X100X10", "150X115X12", "200X150X10", "200X100X12", "150X115X15", "200X150X12", "200X100X15", "200X150X15", "200X150X18" }));
        cb23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb23ActionPerformed(evt);
            }
        });

        L22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        L22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        L23.setBackground(new java.awt.Color(255, 255, 255));
        L23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        L23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout P21Layout = new javax.swing.GroupLayout(P21);
        P21.setLayout(P21Layout);
        P21Layout.setHorizontalGroup(
            P21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P21Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(P21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(L23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(P21Layout.createSequentialGroup()
                        .addGroup(P21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb22, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L21, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(P21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cb23, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(L22, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25))
        );
        P21Layout.setVerticalGroup(
            P21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb23, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L23, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(P21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(L21, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(L22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(P21, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 710, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inputs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Allowable Slenderness Ratio");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 120, 280, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Length of tension member in mm");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 80, 300, 22);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Factored Load in KN");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 40, 190, 22);

        tf21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tf21);
        tf21.setBounds(340, 32, 142, 30);

        tf22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tf22);
        tf22.setBounds(340, 72, 142, 30);

        tf23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf23ActionPerformed(evt);
            }
        });
        jPanel1.add(tf23);
        tf23.setBounds(340, 112, 142, 30);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 500, 160));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/NWEEE2222.jpg"))); // NOI18N
        jLabel16.setText("jLabel16");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -160, 1100, 1040));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf23ActionPerformed

    private void tf27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf27ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void tf25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf25ActionPerformed

    private void chb21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb21ActionPerformed
       if(chb21.isSelected()){
         tf24.setText("410");
         tf24.setEnabled(false);
         tf25.setText("250");
         tf25.setEnabled(false);
      }
       if(!chb21.isSelected()){
         tf24.setEnabled(true);
         tf25.setEnabled(true);
      }
              
           // TODO add your handling code here:
    }//GEN-LAST:event_chb21ActionPerformed

    private void tf29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf29ActionPerformed

    private void tf211ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf211ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf211ActionPerformed

    private void b22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b22ActionPerformed
        this.toBack();
        this.setVisible(false);
        new First().toFront();
        new First().setState(java.awt.Frame.NORMAL);        
        // TODO add your handling code here:
    }//GEN-LAST:event_b22ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        if (tf21.getText().equals("")){
             ninth nn = new ninth();
             nn.setVisible(true);
           }else
        if (tf22.getText().equals("")){
             ninth nn = new ninth();
             nn.setVisible(true);
           }else
        if (tf23.getText().equals("")){
             ninth nn = new ninth();
             nn.setVisible(true);
           }else
        if (tf24.getText().equals("")){
             ninth nn = new ninth();
             nn.setVisible(true);
           }else
        if (tf25.getText().equals("")){
             this.toBack();
             ninth nn = new ninth();
             nn.setVisible(true);
             nn.toFront();
           }else
        if (tf26.getText().equals("")){
             ninth nn = new ninth();
             nn.setVisible(true);
           }else
        if (tf27.getText().equals("")){
             ninth nn = new ninth();
             nn.setVisible(true);
           }else
        if (tf28.getText().equals("")){
             ninth nn = new ninth();
             nn.setVisible(true);
           }else
        if (tf29.getText().equals("")){
             ninth nn = new ninth();
             nn.setVisible(true);
           }else
        if (tf210.getText().equals("")){
             ninth nn = new ninth();
             nn.setVisible(true);
           }else
        if (tf211.getText().equals("")){
             ninth nn = new ninth();
             nn.setVisible(true);
           }else
        if (tf212.getText().equals("")){
             ninth nn = new ninth();
             nn.setVisible(true);
           }else
        if(buttonGroup1.getSelection()==null){
             ninth nn = new ninth();
             nn.setVisible(true);
         }else
        if(buttonGroup3.getSelection()==null){
             ninth nn = new ninth();
             nn.setVisible(true);
        }
        
        //this.toBack();
        boolean b = (L24.getText()=="Double Angle placed same side of gusset plate with bolted connection");
        double[] Ag_eq = {112, 141, 145, 173, 184, 203, 225, 226, 234, 264, 266, 277, 295, 307, 327, 347, 378, 386, 388, 428, 447, 479, 507, 527, 568, 575, 625, 626, 677, 684, 727, 744, 806, 818, 866, 896, 929, 976, 1002, 1047, 1058, 1100, 1138, 1167, 1200, 1221, 1302, 1379, 1402, 1505, 1539, 1702, 1703, 1781, 1903, 2019, 2022, 2106, 2259, 2502, 2506, 2903, 2982, 3081, 3459, 3681, 4278, 4661, 5079, 5780, 6881, 9380};
        double[] Xc_eq = {5.9, 7.1, 6.3, 8.3, 7.5, 9.5, 7.9, 8.7, 10.8, 12, 10, 9.2, 13.2, 11.2, 10.4, 12.5, 11.6, 10.8, 13.7, 12.9, 12, 14.1, 13.3, 15.3, 14.5, 16.5, 17.7, 15.7, 18.9, 16.9, 20.2, 18.1, 19.4, 16.5, 20.6, 17.7, 21.8, 18.9, 17.2, 24.2, 20.2, 18.5, 21.4, 26.7, 19.7, 22.7, 21, 25.1, 22.2, 23.4, 27.6, 30, 25.9, 24.2, 28.4, 26.6, 35, 30.8, 29.2, 31.6, 35.8, 40.6, 36.6, 32.7, 41.4, 37.8, 42.6, 53.6, 43.8, 54.9, 56.1, 58.8};
        //double[] Yc_eq = {14.1, 13.7, 17.9, 17.5, 17.1, 21.7, 21.3, 20.8, 25.5, 25, 24.6, 24.2, 29.2, 28.8, 28.4, 28, 33, 32.5, 32.1, 31.7, 36.8, 36.3, 35.9, 35.5, 39.7, 39.3, 38.5, 37.8, 43.5, 43.1, 42.3, 41.5, 47.3, 46.9, 46.1, 45.3, 51.1, 50.6, 49.8, 49, 54.8, 54.4, 53.6, 52.8, 52.8, 57.3, 56.6, 55.8, 65.8, 64.9, 64.1, 63.4, 73.3, 72.4, 71.6, 70.8, 80, 79.2, 78.4, 77.3, 95, 94.2, 93.4, 92.2, 109.4, 108.6, 107.4, 106.2, 146.4, 145.1, 143.9, 141.2};
        double[] Rmin_eq = {7.3, 9.3, 7.2, 11.3, 9.1, 13.3, 9.1, 11.2, 15.4, 17.4, 13.2, 11.1, 19.4, 15.3, 13.1, 17.3, 15.1, 12.9, 19.3, 17.2, 15, 19.2, 17, 21.1, 19, 23.1, 25.1, 21, 27.1, 22.9, 29.2, 25, 27, 20.7, 29.1, 22.7, 31.1, 24.7, 20.3, 35, 26.7, 22.3, 28.8, 39.1, 24.4, 30.8, 26.4, 34.7, 28.4, 30.4, 38.8, 42.8, 34.4, 30.1, 38.5, 34.1, 51, 42.5, 38.2, 42.2, 50.7, 58.6, 50.3, 41.7, 58.3, 49.8, 57.8, 78.4, 57.3, 77.9, 77.5, 76.3};
        double[] Ag_uneq = {141, 184, 188, 218, 225, 234, 246, 286, 302, 307, 352, 356, 378, 416, 447, 476, 526, 552, 565, 602, 625, 627, 656, 716, 737, 746, 817, 858, 865, 938, 955, 978, 1014, 1052, 1137, 1152, 1166, 1202, 1257, 1286, 1336, 1401, 1538, 1551, 1650, 1657, 1698, 1742, 1902, 1956, 2058, 2102, 2156, 2498, 2552, 2562, 2903, 3038, 3400, 3459, 3752, 4056, 4278, 5025, 5976};
        double[] Xc_uneq = {9.8, 10.2, 13, 14.2, 10.6, 16.3, 13.5, 14.7, 13.9, 16.8, 15.1, 14.3, 17.2, 15.5, 17.6, 19.5, 20.7, 22.7, 19.9, 23.9, 21.1, 26, 23.2, 24.4, 20.7, 26.4, 21.9, 24, 28.7, 25.2, 31.9, 27.2, 30.1, 24.8, 29.6, 26, 40.5, 28.1, 32.8, 37, 31, 30.4, 41.5, 33.7, 31.9, 31.2, 38, 52.3, 42.4, 32.7, 44.6, 38.8, 52.3, 39.6, 45.5, 54.1, 69.6, 46.4, 59.9, 70.5, 47.6, 60.8, 71.8, 62, 63.3}; 
        double[] Yc_uneq = {4.9, 5.3, 5.7, 6.9, 5.7, 6.5, 6.2, 7.3, 6.6, 7, 7.7, 6.9, 7.4, 8.1, 7.8, 9.6, 10.8, 10.4, 10, 11.6, 11.2, 11.2, 10.9, 12, 10.8, 11.6, 12, 11.6, 13.9, 12.8, 14.7, 12.4, 17.8, 12.4, 14.8, 13.6, 15.9, 13.2, 15.5, 22.2, 18.7, 15.5, 16.8, 16.3, 19.5, 16.3, 23.1, 15.3, 17.6, 20.3, 27.3, 23.9, 16.1, 24.7, 28.2, 16.9, 20.1, 29, 35.1, 21, 30.2, 36, 22.2, 37.2, 38.4};
        double[] Rmin_uneq = {4.1, 4.1, 5.2, 6.3, 4.1, 6.5, 5.2, 6.3, 5.2, 6.3, 6.3, 5.2, 6.3, 6.3, 6.3, 8.5, 9.6, 9.6, 8.5, 10.7, 9.5, 10.7, 9.6, 10.7, 8.4, 10.7, 9.5, 9.5, 12.8, 10.6, 13.9, 10.6, 15.9, 9.5, 12.8, 10.6, 16.2, 10.6, 13.9, 20.3, 15.9, 12.7, 16.1, 13.8, 15.8, 12.7, 20.2, 16, 16.1, 15.8, 24.5, 20.2, 15.9, 20.1, 24.4, 15.8, 21.4, 24.4, 32.1, 21.3, 24.3, 32.1, 21.2, 32, 31.9};       
       
        double FL = Double.parseDouble(tf21.getText());
        double Lten = Double.parseDouble(tf22.getText());
        double SR = Double.parseDouble(tf23.getText());
        double Fu = Double.parseDouble(tf24.getText());
        double Fy = Double.parseDouble(tf25.getText());
        double ym1 = Double.parseDouble(tf26.getText());
        double ym0 = Double.parseDouble(tf27.getText());
        double Fub = Double.parseDouble(tf28.getText());
        double d = Double.parseDouble(tf29.getText());
        double p = Double.parseDouble(tf210.getText());   
        double e = Double.parseDouble(tf211.getText());   
        double ymf = Double.parseDouble(tf212.getText()); 
        double L,B,t;
        if(rb26.isSelected()){
          Tenth out = new Tenth();
          out.yeah.append("---------------------------------------------------------------");
          out.yeah.append("\nInputs: ");
          out.yeah.append("\nFactored Load                       "+FL+" kN");
          out.yeah.append("\nLength of Tension Member            "+Lten+" mm");
          out.yeah.append("\nAllowable Slenderness Ratio         "+SR);
          out.yeah.append("\nType of Section                     "+L23.getText());
          out.yeah.append("\nUltimate Stress of Steel            "+Fu+" N/mm^2");
          out.yeah.append("\nYield Stress of Steel               "+Fy+" N/mm^2");
          out.yeah.append("\nPartial Safety Factor governed by:          ");
          out.yeah.append("\nUltimate Stress(ym1)                "+ym1);
          out.yeah.append("\nYielding(ym0)                       "+ym0);
          out.yeah.append("\nUltimate Strength of Bolt           "+Fub+" N/mm^2");
          out.yeah.append("\nDiameter of Bolt                    "+d+" mm");
          out.yeah.append("\nPartial Safety factor for Bolts     "+ymf);
          out.yeah.append("\n---------------------------------------------------------------");
          int idx=0;
          String sec= "";
          double Rmin = 0,ISA=0;
          if(rb23.isSelected()){
             sec = (String)cb22.getSelectedItem(); 
             idx = cb22.getSelectedIndex(); 
             Rmin = Rmin_eq[idx];
             ISA = Ag_eq[idx];
          }
          if(rb24.isSelected()){
             sec = (String)cb23.getSelectedItem();
             idx = cb23.getSelectedIndex();
             Rmin = Rmin_uneq[idx];
             ISA = Ag_uneq[idx];
          }
          String[] res = sec.split("X");
          //System.out.println("hurray");
          L = Double.parseDouble(res[0]); 
          B = Double.parseDouble(res[1]); 
          t = Double.parseDouble(res[2]); 
          
          double Ag = (double)Math.round(((FL*ym0)/Fy)*1000000)/1000;
          
          out.yeah.append("\nRequired Area of Cross Section area is: "+Ag+" mm^2");
          out.yeah.append("\nSection choosen is ISA "+sec+" with cross sectional area of "+ISA+" mm^2");
          if(b){
           out.yeah.append("\nTotal cross sectional area(combined) = 2x"+ISA+" = ");
           ISA = 2*ISA;
           out.yeah.append(""+ISA+" mm^2");
           }
          if(ISA<Ag){
           out.yeah.append("\nAs we can see,( "+ISA+" < "+Ag+" ), this section is not meeting this requirement, hence this section can't be choosen");
           out.L10.setText("The chosen section, "+L23.getText()+" cannot sustain the given load condition");
          }
          else{
           double Fs = (double)Math.round(((0.78*Math.PI*d*d*Fub)/(4*ymf*Math.sqrt(3))))/1000;
           double Kb = (double)Math.round(Math.min(Math.min(e/(3*(d+2)),(p/(3*(d+2))-0.25)),Math.min(Fub/Fu,1))*1000)/1000;
           //System.out.println(Kb);
           double Fb = (double)Math.round(2.5*Kb*d*t*Fu/ymf)/1000;
           out.yeah.append("\nShearing strength of one bolt is "+Fs+" kN");
           out.yeah.append("\nBearing strength of one bolt is "+Fb+" kN");
           double Nb = (double)Math.round(FL*1000/Math.min(Fs,Fb))/1000;
           double N = (double)Math.ceil(Nb);
           out.yeah.append("\nNumber of bolts = Factored Load/Minimum of Shearing and Bearing Strength = "+Nb);
           out.yeah.append("\nNumber of bolts for this factored load is "+(int)N);
           out.yeah.append("\n");
           out.yeah.append("\n");
           out.yeah.append("\n->Gross Section Yielding:");
           double Tdg = (double)Math.round(ISA*Fy/ym0)/1000;
           out.yeah.append("\nTdg = AgxFy/ymf\nTdg = "+Tdg+" kN");
           if(Tdg<FL){
            out.yeah.append("\nAs we can see,( "+FL+" < "+Tdg+" ), this section is not meeting this requirement, hence this section can't be choosen"); 
            out.L10.setText("The chosen section, "+sec+" cannot sustain the given load condition");
           }else{
           out.yeah.append("\n");
           out.yeah.append("\n");
           out.yeah.append("\n->Check for net section rupture:");
           double alpha = 0.8;
           if(N==1||N==2){
              alpha = 0.6;
             }else if(N==3){
              alpha = 0.7;
              }else if(N>4){
               alpha = 0.8;
              } 
           double An = (L+B-t-d-2)*t;
           double Tdn = (double)Math.round((alpha*An*Fu)/ym1)/1000;
            out.yeah.append("\nalpha = "+alpha+" calculated from the number of bolts");
            out.yeah.append("\nAn = "+An+" mm^2");
            out.yeah.append("\nTdn = alpha x An x fu/ym1");
            out.yeah.append("\nTdn = "+Tdn+" kN");
            if(b){
           Tdn = 2*Tdn;
           out.yeah.append("\nTotal Tdn(combined) = 2xTdn = "+Tdn+" kN");
           }
           if(Tdn<FL){
             out.yeah.append("\nAs we can see,( "+Tdn+" < "+FL+" ), this section is not meeting this requirement, hence this section can't be choosen");
             out.L10.setText("The chosen section, "+sec+" cannot sustain the given load condition");
           }else{
            out.yeah.append("\n");
            out.yeah.append("\n");
            out.yeah.append("\n->Block Shear Failure:");
            //out.yeah.append("\n->Maximum and minimum value of guage distance calculated is "+gmax+" mm and "+gmin+" mm respectively.");
            double Avg = t*((N-1)*p+e);
            double Avn = t*((N-1)*p+e-(N-0.5)*(d+2));
            double val = 0;
            if(cb21.getSelectedIndex()==1){
                val = L - (int)(Math.ceil((L-t)/2));
            }
            if(cb21.getSelectedIndex()==0){
                val = B - (int)(Math.ceil((B-t)/2));
            }
            double Atg = t*val;
            double Atn = t*(val-(d+2)/2);
            out.yeah.append("\nAvg = "+Avg+" mm^2");
            out.yeah.append("\nAvn = "+Avn+" mm^2");
            out.yeah.append("\nAtg = "+Atg+" mm^2");
            out.yeah.append("\nAtn = "+Atn+" mm^2");
            double Tdb1 =  (double)Math.round(0.9*Avn*Fu/(Math.sqrt(3)*ym1) + Atg*Fy/ym0)/1000;
            double Tdb2 =  (double)Math.round(Avg*Fy/(Math.sqrt(3)*ym0) + 0.9*Atn*Fu/ym1)/1000;
            double Tdb = Math.min(Tdb1,Tdb2);
            out.yeah.append("\nTdb1 = 0.9xAvnxFu/(root(3)xym1) + AtgxFy/ym0= "+Tdb1+" kN");
            out.yeah.append("\nTdb2 = AvgxFy/(Math.sqrt(3)xym0) + 0.9xAtnxFu/ym1 = "+Tdb2+" kN");
            out.yeah.append("\nTdb = Min(Tdb1,Tdb2) = "+Tdb+" kN");
            if(b){
            Tdb = 2*Tdb;
            out.yeah.append("\nTotal Tdb(combined) = 2xTdb = "+Tdb+" kN");
            }
            if(Tdb<FL){
            out.yeah.append("\nAs we can see,( "+Tdb+" < "+FL+" ), this section is not meeting this requirement, hence this section can't be choosen");
            out.L10.setText("The chosen section, "+sec+" cannot sustain the given load condition");
                }else{
             out.yeah.append("\n");
             out.yeah.append("\n");
             out.yeah.append("\n->Check for Slenderness Ratio:"); 
             double lambda = (double)Math.round(Lten*1000/Rmin)/1000;
             out.yeah.append("\nlambda = Length of Tension Member/Rvv = "+Lten+"/"+Rmin+" = "+lambda);
             if(lambda>SR){
                 out.yeah.append("\nAs we can see,( "+lambda+" > "+SR+" ), this section is not meeting this requirement, hence this section can't be choosen");
                 out.L10.setText("The chosen section, "+sec+" cannot sustain the given load condition");
                   }else{
                 out.yeah.append("\nAs we can see,( "+lambda+" < "+SR+" ), so OK");
                 out.yeah.append("\nHence, the choosen section is "+sec+" is OK under the given load configuration");
                 out.L10.setText("The chosen section, "+sec+" is OK and can sustain the given load condition");
                  }
                }
              }
            }           
          }
          out.L111.setText(L24.getText());
          out.yeah.setEditable(false);
          out.setVisible(true);
        }
   if(rb25.isSelected()){
          Tenth out = new Tenth();
          out.yeah.append("---------------------------------------------------------------");
          out.yeah.append("\nInputs: ");
          out.yeah.append("\nFactored Load                       "+FL+" kN");
          out.yeah.append("\nLength of Tension Member            "+Lten+" mm");
          out.yeah.append("\nAllowable Slenderness Ratio         "+SR);
          out.yeah.append("\nType of Section                     "+L23.getText());
          out.yeah.append("\nUltimate Stress of Steel            "+Fu+" N/mm^2");
          out.yeah.append("\nYield Stress of Steel               "+Fy+" N/mm^2");
          out.yeah.append("\nPartial Safety Factor governed by:          ");
          out.yeah.append("\nUltimate Stress(ym1)                "+ym1);
          out.yeah.append("\nYielding(ym0)                       "+ym0);
          out.yeah.append("\nUltimate Strength of Bolt           "+Fub+" N/mm^2");
          out.yeah.append("\nDiameter of Bolt                    "+d+" mm");
          out.yeah.append("\nPartial Safety factor for Bolts     "+ymf);
          out.yeah.append("\n---------------------------------------------------------------");
          int idx=0;
          int k = 1;
          double lambda = 10000;
          double Ag = (double)Math.round(((FL*ym0)/Fy)*1000000)/1000;
          out.yeah.append("\nRequired Area of Cross Section area is: "+Ag+" mm^2");
          while(lambda>SR){
          String sec= "";
          double Rmin = 0,ISA=0;
          if(rb23.isSelected()){
              if(idx==72){
              out.L10.setText("There exist no "+L23.getText()+" section that can sustain the given load condition");
              break;
              }
             cb22.setSelectedIndex(idx);
             ISA = Ag_eq[idx];
             sec = (String)cb22.getSelectedItem(); 
             idx = cb22.getSelectedIndex(); 
             Rmin = Rmin_eq[idx];             
          }
          if(rb24.isSelected()){
              if(idx==65){
              out.L10.setText("There exist no "+L23.getText()+" section that can sustain the given load condition");
              break;
              }
             cb23.setSelectedIndex(idx);
             ISA = Ag_uneq[idx];
             sec = (String)cb23.getSelectedItem();
             idx = cb23.getSelectedIndex();
             Rmin = Rmin_uneq[idx];             
          } 
          double ISA1 = ISA;
          if(b){
           ISA1 = ISA;
           ISA =2*ISA; 
          }
          if(ISA<Ag){
          // out.yeah.append("\nAs we can see,( "+ISA+" < "+Ag+" ), this section is not meeting this requirement, Let's, try another section "); 
          idx++;
          continue;
          }
          out.yeah.append("\n");
          out.yeah.append("\nTest Case "+k+":");
          k++;
          out.yeah.append("\n");
          String[] res = sec.split("X");
          //System.out.println("hurray");
          L = Double.parseDouble(res[0]); 
          B = Double.parseDouble(res[1]); 
          t = Double.parseDouble(res[2]);  
          out.yeah.append("\nSection choosen is ISA "+sec+" with cross sectional area of "+ISA1+" mm^2");
          if(b){
           out.yeah.append("\nTotal cross sectional area(combined) = 2x"+ISA1+" = ");
           out.yeah.append(""+ISA+" mm^2");
           }
           double Fs = (double)Math.round(((0.78*Math.PI*d*d*Fub)/(4*ymf*Math.sqrt(3))))/1000;
           double Kb = (double)Math.round(Math.min(Math.min(e/(3*(d+2)),(p/(3*(d+2))-0.25)),Math.min(Fub/Fu,1))*1000)/1000;
           //System.out.println(Kb);
           double Fb = (double)Math.round(2.5*Kb*d*t*Fu/ymf)/1000;
           out.yeah.append("\nShearing strength of one bolt is "+Fs+" kN");
           out.yeah.append("\nBearing strength of one bolt is "+Fb+" kN");
           double N =0,Nb=0;
           if(b){
           Nb = (double)Math.round(FL*1000/(2*Math.min(Fs,Fb)))/1000;
           N = (double)Math.ceil(Nb);
           out.yeah.append("\nNumber of bolts per ISA section = Factored Load/(2xMinimum of Shearing and Bearing Strength) = "+Nb);
           out.yeah.append("\nNumber of bolts for this factored load for each ISA section is "+(int)N);
           }else{
           Nb = (double)Math.round(FL*1000/Math.min(Fs,Fb))/1000;
           N = (double)Math.ceil(Nb);
           out.yeah.append("\nNumber of bolts = Factored Load/Minimum of Shearing and Bearing Strength = "+Nb);
           out.yeah.append("\nNumber of bolts for this factored load is "+(int)N); 
           }
           out.yeah.append("\n");
           out.yeah.append("\n");
           out.yeah.append("\n->Gross Section Yielding:");
           double Tdg = (double)Math.round(ISA*Fy/ym0)/1000;
           out.yeah.append("\nTdg = AgxFy/ymf\nTdg = "+Tdg+" kN");
           if(Tdg<FL){
            out.yeah.append("\nAs we can see,( "+FL+" < "+Tdg+" ), this section is not meeting this requirement, Let's, try another section"); 
            idx++;
            continue;
           }else{
           out.yeah.append("\n");
           out.yeah.append("\n");
           out.yeah.append("\n->Check for net section rupture:");
           double alpha = 0.8;
           if(N==1||N==2){
              alpha = 0.6;
             }else if(N==3){
              alpha = 0.7;
              }else if(N>4){
               alpha = 0.8;
              } 
           double An = (L+B-t-d-2)*t;
           double Tdn = (double)Math.round((alpha*An*Fu)/ym1)/1000;
            out.yeah.append("\nalpha = "+alpha+" calculated from the number of bolts");
            out.yeah.append("\nAn = "+An+" mm^2");
            out.yeah.append("\nTdn = alpha x An x fu/ym1");
            out.yeah.append("\nTdn = "+Tdn+" kN");
            if(b){
            Tdn = 2*Tdn;
            out.yeah.append("\nTotal Tdn(combined) = 2xTdn = "+Tdn+" kN");
            }
           if(Tdn<FL){
             out.yeah.append("\nAs we can see,( "+Tdn+" < "+FL+" ), this section is not meeting this requirement, Let's, try another section");
             idx++;
             continue;
           }else{
            out.yeah.append("\n");
            out.yeah.append("\n");
            out.yeah.append("\n->Block Shear Failure:");
            //out.yeah.append("\n->Maximum and minimum value of guage distance calculated is "+gmax+" mm and "+gmin+" mm respectively.");
            double Avg = t*((N-1)*p+e);
            double Avn = t*((N-1)*p+e-(N-0.5)*(d+2));
            double val = 0;
            if(cb21.getSelectedIndex()==1){
                val = L - (int)(Math.ceil((L-t)/2));
            }
            if(cb21.getSelectedIndex()==0){
                val = B - (int)(Math.ceil((B-t)/2));
            }
            double Atg = t*val;
            double Atn = t*(val-(d+2)/2);
            out.yeah.append("\nAvg = "+Avg+" mm^2");
            out.yeah.append("\nAvn = "+Avn+" mm^2");
            out.yeah.append("\nAtg = "+Atg+" mm^2");
            out.yeah.append("\nAtn = "+Atn+" mm^2");
            double Tdb1 =  (double)Math.round(0.9*Avn*Fu/(Math.sqrt(3)*ym1) + Atg*Fy/ym0)/1000;
            double Tdb2 =  (double)Math.round(Avg*Fy/(Math.sqrt(3)*ym0) + 0.9*Atn*Fu/ym1)/1000;
            double Tdb = Math.min(Tdb1,Tdb2);
            out.yeah.append("\nTdb1 = 0.9xAvnxFu/(root(3)xym1) + AtgxFy/ym0= "+Tdb1+" kN");
            out.yeah.append("\nTdb2 = AvgxFy/(Math.sqrt(3)xym0) + 0.9xAtnxFu/ym1 = "+Tdb2+" kN");
            out.yeah.append("\nTdb = Min(Tdb1,Tdb2) = "+Tdb+" kN");
            if(b){
            Tdb = 2*Tdb;
            out.yeah.append("\nTotal Tdb(combined) = 2xTdb = "+Tdb+" kN");
            }
            if(Tdb<FL){
            out.yeah.append("\nAs we can see,( "+Tdb+" < "+FL+" ), this section is not meeting this requirement, Let's, try another section");
            idx++;
            continue;
                }else{
             out.yeah.append("\n");
             out.yeah.append("\n");
             out.yeah.append("\n->Check for Slenderness Ratio:"); 
             lambda = (double)Math.round(Lten*1000/Rmin)/1000;
             out.yeah.append("\nlambda = Length of Tension Member/Rvv = "+Lten+"/"+Rmin+" = "+lambda);
             if(lambda>SR){
                 out.yeah.append("\nAs we can see,( "+lambda+" > "+SR+" ), this section is not meeting this requirement, Let's, try another section");
                 idx++;
                 continue;
                   }else{
                 out.yeah.append("\nAs we can see,( "+lambda+" < "+SR+" ), so OK");
                 out.yeah.append("\nHence, the choosen section, "+sec+" is OK and the OPTIMUM ONE under the given load configuration");
                 out.L10.setText("The choosen section is "+sec+", is OK and the OPTIMUM ONE under the given load configuration");
                 break;
                  }
                }
              }
            }         
          }  
          out.L111.setText(L24.getText());
          out.yeah.setEditable(false);
          out.setVisible(true);       
      }                
// TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    private void tf26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf26ActionPerformed

    private void tf28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf28ActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_tf28ActionPerformed

    private void rb21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb21ActionPerformed
     if(rb21.isSelected()== true){
         tf28.setText("400");
         tf28.setEnabled(false);
      }     
        // TODO add your handling code here:
    }//GEN-LAST:event_rb21ActionPerformed

    private void rb22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb22ActionPerformed
     if(rb22.isSelected()== true){
         tf28.setText("800");
         tf28.setEnabled(false);
      }    
        // TODO add your handling code here:
    }//GEN-LAST:event_rb22ActionPerformed

    private void chb22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb22ActionPerformed
       if(chb22.isSelected()){
         tf26.setText("1.25");
         tf26.setEnabled(false);
         tf27.setText("1.1");
         tf27.setEnabled(false);
      }   
       if(!chb22.isSelected()){
         tf26.setEnabled(true);
         tf27.setEnabled(true);
      }
        // TODO add your handling code here:
    }//GEN-LAST:event_chb22ActionPerformed

    private void chb24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb24ActionPerformed
      if(chb24.isSelected()){
         tf210.setText("50");
         tf210.setEnabled(false);
         tf211.setText("30");
         tf211.setEnabled(false);
      }
      if(!chb24.isSelected()){
         tf210.setEnabled(true);
         tf211.setEnabled(true);
      }
        // TODO add your handling code here:
    }//GEN-LAST:event_chb24ActionPerformed

    private void chb25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb25ActionPerformed
    if(chb25.isSelected()){
         tf212.setText("1.25");
         tf212.setEnabled(false);
      }
    if(!chb25.isSelected()){
         tf212.setEnabled(true);
      }
        // TODO add your handling code here:
    }//GEN-LAST:event_chb25ActionPerformed

    private void tf24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf24ActionPerformed

    private void cb21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb21ActionPerformed
    L23.setText("Unequal with "+ cb21.getSelectedItem());
        // TODO add your handling code here:
    }//GEN-LAST:event_cb21ActionPerformed

    private void rb23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb23ActionPerformed
     if(rb23.isSelected()){
      cb21.setEnabled(false);
      cb23.setEnabled(false);
      cb22.setEnabled(true);
     }
     if(rb25.isSelected()){
      cb23.setEnabled(false);
      cb22.setEnabled(false);
     }
     L23.setText("Equal");
        // TODO add your handling code here:
    }//GEN-LAST:event_rb23ActionPerformed

    private void rb24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb24ActionPerformed
      if(rb24.isSelected()){
      cb21.setEnabled(true);
      cb23.setEnabled(true);
      cb22.setEnabled(false);
     }
      if(rb25.isSelected()){
      cb23.setEnabled(false);
      cb22.setEnabled(false);
     }
     
        // TODO add your handling code here:
    }//GEN-LAST:event_rb24ActionPerformed

    private void rb25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb25ActionPerformed
      if(rb25.isSelected()){
      cb23.setEnabled(false);
      cb22.setEnabled(false);
     }  
        // TODO add your handling code here:
    }//GEN-LAST:event_rb25ActionPerformed

    private void rb26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb26ActionPerformed
    if(rb26.isSelected()){
         if(rb23.isSelected())
         {
      cb21.setEnabled(false);
      cb23.setEnabled(false);
      cb22.setEnabled(true);
         }else 
      if(rb24.isSelected())
         {
      cb21.setEnabled(true);
      cb23.setEnabled(true);
      cb22.setEnabled(false);
         }else{
      cb21.setEnabled(true);
      cb23.setEnabled(true);
      cb22.setEnabled(true);
      }
     }  
        // TODO add your handling code here:
    }//GEN-LAST:event_rb26ActionPerformed

    private void cb22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb22ActionPerformed
      
      L21.setText("Choosen section : ");
      L22.setText("" + cb22.getSelectedItem());         
        // TODO add your handling code here:
    }//GEN-LAST:event_cb22ActionPerformed

    private void cb23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb23ActionPerformed
      L21.setText("Choosen section : ");
      L22.setText("" + cb23.getSelectedItem()); 
      
        
        // TODO add your handling code here:
    }//GEN-LAST:event_cb23ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Second_Java.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Second_Java.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Second_Java.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Second_Java.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Second_Java().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L21;
    private javax.swing.JLabel L22;
    private javax.swing.JLabel L23;
    public static javax.swing.JLabel L24;
    private javax.swing.JPanel P21;
    private javax.swing.JButton b22;
    public static javax.swing.JButton b3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    public static javax.swing.JComboBox<String> cb21;
    private javax.swing.JComboBox<String> cb22;
    private javax.swing.JComboBox<String> cb23;
    private javax.swing.JCheckBox chb21;
    private javax.swing.JCheckBox chb22;
    private javax.swing.JCheckBox chb24;
    private javax.swing.JCheckBox chb25;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JRadioButton rb21;
    private javax.swing.JRadioButton rb22;
    public static javax.swing.JRadioButton rb23;
    public static javax.swing.JRadioButton rb24;
    public static javax.swing.JRadioButton rb25;
    public static javax.swing.JRadioButton rb26;
    public static javax.swing.JRadioButton rb45;
    public static javax.swing.JRadioButton rb46;
    private javax.swing.JTextField tf21;
    private javax.swing.JTextField tf210;
    private javax.swing.JTextField tf211;
    private javax.swing.JTextField tf212;
    private javax.swing.JTextField tf22;
    private javax.swing.JTextField tf23;
    private javax.swing.JTextField tf24;
    private javax.swing.JTextField tf25;
    private javax.swing.JTextField tf26;
    private javax.swing.JTextField tf27;
    private javax.swing.JTextField tf28;
    private javax.swing.JTextField tf29;
    // End of variables declaration//GEN-END:variables
}
