

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ShikariX
 */
public class Third_ extends javax.swing.JFrame {

    /**
     * Creates new form Third_
     */
    public Third_() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        L34 = new javax.swing.JLabel();
        b33 = new javax.swing.JButton();
        P22 = new javax.swing.JPanel();
        cb32 = new javax.swing.JComboBox<>();
        cb33 = new javax.swing.JComboBox<>();
        L31 = new javax.swing.JLabel();
        L33 = new javax.swing.JLabel();
        L32 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf31 = new javax.swing.JTextField();
        tf32 = new javax.swing.JTextField();
        tf33 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        rb35 = new javax.swing.JRadioButton();
        rb36 = new javax.swing.JRadioButton();
        cb31 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        tf34 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tf35 = new javax.swing.JTextField();
        rb33 = new javax.swing.JRadioButton();
        rb34 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        chb31 = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        tf36 = new javax.swing.JTextField();
        tf37 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        chb32 = new javax.swing.JCheckBox();
        tf38 = new javax.swing.JTextField();
        tf39 = new javax.swing.JTextField();
        b32 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        rb38 = new javax.swing.JRadioButton();
        rb37 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        L34.setFont(new java.awt.Font("Ubuntu Mono", 1, 24)); // NOI18N
        L34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(L34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1050, 60));

        b33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/oitt.jpg"))); // NOI18N
        b33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b33ActionPerformed(evt);
            }
        });
        getContentPane().add(b33, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 600, 250, 110));

        P22.setBackground(new java.awt.Color(255, 255, 255));
        P22.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Choose Section", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        cb32.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        cb32.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "20X20X3", "25X25X3", "20X20X4", "30X30X3", "25X25X4", "35X35X3", "25X25X5", "30X30X4", "40X40X3", "45X45X3", "35X35X4", "30X30X5", "50X50X3", "40X40X4", "35X35X5", "45X45X4", "40X40X5", "35X35X6", "50X50X4", "45X45X5", "40X40X6", "50X50X5", "45X45X6", "55X55X5", "50X50X6", "60X60X5", "65X65X5", "55X55X6", "70X70X5", "60X60X6", "75X75X5", "65X65X6", "70X70X6", "55X55X8", "75X75X6", "60X60X8", "80X80X6", "65X65X8", "55X55X10", "90X90X6", "70X70X8", "60X60X10", "75X75X8", "100X100X6", "65X65X10", "80X80X8", "70X70X10", "90X90X8", "75X75X10", "80X80X10", "100X100X8", "110X110X8", "90X90X10", "80X80X12", "100X100X10", "90X90X12", "130X130X8", "110X110X10", "100X100X12", "110X110X12", "130X130X10", "150X150X10", "130X130X12", "110X110X15", "150X150X12", "130X130X15", "150X150X15", "200X200X12", "150X150X18", "200X200X15", "200X200X18", "200x200X25" }));
        cb32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb32ActionPerformed(evt);
            }
        });

        cb33.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        cb33.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "30X20X3", "30X20X4", "40X25X3", "45X30X3", "30X20X5", "50X30X3", "40X25X4", "45X30X4", "40X25X5", "50X30X4", "45X30X5", "40X25X6", "50X30X5", "45X30X6", "50X30X6", "60X40X5", "65X45X5", "7045X5", "60X40X6", "75X50X5", "65X45X6", "80X50X5", "70X45X6", "75X50X6", "60X40X8", "80X50X6", "65X45X8", "70X45X8", "90X60X6", "75X50X8", "100X65X6", "80X50X8", "100X75X6", "70X45X10", "90X60X8", "75X50X10", "125X75X6", "80X50X10", "100X65X8", "125X95X6", "100X75X8", "90X60X10", "125X75X8", "100X65X10", "100X75X10", "90X60X12", "125X95X8", "150X75X8", "125X75X10", "100X75X12", "150X115X8", "125X95X10", "150X75X10", "125X95X12", "150X115X10", "150X75X12", "200X100X10", "150X115X12", "200X150X10", "200X100X12", "150X115X15", "200X150X12", "200X100X15", "200X150X15", "200X150X18" }));
        cb33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb33ActionPerformed(evt);
            }
        });

        L31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        L31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        L33.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        L32.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        L32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout P22Layout = new javax.swing.GroupLayout(P22);
        P22.setLayout(P22Layout);
        P22Layout.setHorizontalGroup(
            P22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P22Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(P22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P22Layout.createSequentialGroup()
                        .addComponent(cb32, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cb33, 0, 227, Short.MAX_VALUE))
                    .addGroup(P22Layout.createSequentialGroup()
                        .addComponent(L33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(L32, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(L31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        P22Layout.setVerticalGroup(
            P22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(P22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb32, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb33, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(L31, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(P22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(P22Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(L33, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(P22Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(L32, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(P22, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 540, 510, 160));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inputs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Factored Load in KN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Length of tension member in mm");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Allowable Slenderness Ratio");

        tf31.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        tf32.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        tf33.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf33ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf31, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tf33, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                        .addComponent(tf32)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf31))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tf32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tf33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Type Of Section", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        buttonGroup3.add(rb35);
        rb35.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rb35.setText("Equal");
        rb35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb35ActionPerformed(evt);
            }
        });

        buttonGroup3.add(rb36);
        rb36.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rb36.setText("Unequal");
        rb36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb36ActionPerformed(evt);
            }
        });

        cb31.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cb31.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Outstanding Leg Larger", "Connected Leg Larger" }));
        cb31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb31ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(rb36)
                        .addGap(86, 86, 86)
                        .addComponent(cb31, 0, 299, Short.MAX_VALUE))
                    .addComponent(rb35))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(rb35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb36)
                    .addComponent(cb31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 510, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Properties of Weld", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Throat Thickness in mm");

        tf34.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Partial Safety Factors", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Custom Safety Factor(ymb)");

        tf35.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf35ActionPerformed(evt);
            }
        });

        buttonGroup2.add(rb33);
        rb33.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rb33.setText("Shop Welding");
        rb33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb33ActionPerformed(evt);
            }
        });

        buttonGroup2.add(rb34);
        rb34.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rb34.setText("Site Welding");
        rb34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb34ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb33)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb34, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf35, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb33)
                    .addComponent(rb34))
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf34, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tf34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 520, 210));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Properties of Steel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        chb31.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chb31.setText("Fe410 Steel");
        chb31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb31ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Ultimate Tensile Stress in Mpa");

        tf36.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf36ActionPerformed(evt);
            }
        });

        tf37.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf37ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Yield Stress in MPa");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Partial Safety Factors", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Governed by ultimate strength (ym1)");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Governed by yielding (ym0)");

        chb32.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chb32.setText("Take according to IS800 table 5 (cl. 5.4.1)");
        chb32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb32ActionPerformed(evt);
            }
        });

        tf38.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        tf39.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tf39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf39ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chb32)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf38, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf39, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(chb32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(56, 56, 56)
                                .addComponent(tf36))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(chb31)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(145, 145, 145)
                                .addComponent(tf37)))
                        .addGap(24, 24, 24))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chb31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tf36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 510, 330));

        b32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/baclkk.jpg"))); // NOI18N
        b32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b32ActionPerformed(evt);
            }
        });
        getContentPane().add(b32, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, 120, 110));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Type of Design", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        buttonGroup4.add(rb38);
        rb38.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rb38.setText("Check for particular section");
        rb38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb38ActionPerformed(evt);
            }
        });

        buttonGroup4.add(rb37);
        rb37.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rb37.setText("Design for economical section");
        rb37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb37ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rb37)
                    .addComponent(rb38))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(rb37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb38)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 520, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/NWEEE2222.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b33ActionPerformed
        if (tf31.getText().equals("")){
             ninth nn = new ninth();
             nn.setVisible(true);
           }else
        if (tf32.getText().equals("")){
             ninth nn = new ninth();
             nn.setVisible(true);
           }else
        if (tf33.getText().equals("")){
             ninth nn = new ninth();
             nn.setVisible(true);
           }else
        if (tf34.getText().equals("")){
             ninth nn = new ninth();
             nn.setVisible(true);
           }else
        if (tf35.getText().equals("")){
             this.toBack();
             ninth nn = new ninth();
             nn.setVisible(true);
             nn.toFront();
           }else
        if (tf36.getText().equals("")){
             ninth nn = new ninth();
             nn.setVisible(true);
           }else
        if (tf37.getText().equals("")){
             ninth nn = new ninth();
             nn.setVisible(true);
           }else
        if (tf38.getText().equals("")){
             ninth nn = new ninth();
             nn.setVisible(true);
           }else
        if (tf39.getText().equals("")){
             ninth nn = new ninth();
             nn.setVisible(true);
           }else
        if(buttonGroup3.getSelection()==null){
             ninth nn = new ninth();
             nn.setVisible(true);
         }else
        if(buttonGroup4.getSelection()==null){
             ninth nn = new ninth();
             nn.setVisible(true);
        } 
        boolean c = (L34.getText()=="Double Angle placed opposite side of gusset plate with welded connection");
        //this.toBack();
        double[] Ag_eq = {112, 141, 145, 173, 184, 203, 225, 226, 234, 264, 266, 277, 295, 307, 327, 347, 378, 386, 388, 428, 447, 479, 507, 527, 568, 575, 625, 626, 677, 684, 727, 744, 806, 818, 866, 896, 929, 976, 1002, 1047, 1058, 1100, 1138, 1167, 1200, 1221, 1302, 1379, 1402, 1505, 1539, 1702, 1703, 1781, 1903, 2019, 2022, 2106, 2259, 2502, 2506, 2903, 2982, 3081, 3459, 3681, 4278, 4661, 5079, 5780, 6881, 9380};
        double[] Xc_eq = {5.9, 7.1, 6.3, 8.3, 7.5, 9.5, 7.9, 8.7, 10.8, 12, 10, 9.2, 13.2, 11.2, 10.4, 12.5, 11.6, 10.8, 13.7, 12.9, 12, 14.1, 13.3, 15.3, 14.5, 16.5, 17.7, 15.7, 18.9, 16.9, 20.2, 18.1, 19.4, 16.5, 20.6, 17.7, 21.8, 18.9, 17.2, 24.2, 20.2, 18.5, 21.4, 26.7, 19.7, 22.7, 21, 25.1, 22.2, 23.4, 27.6, 30, 25.9, 24.2, 28.4, 26.6, 35, 30.8, 29.2, 31.6, 35.8, 40.6, 36.6, 32.7, 41.4, 37.8, 42.6, 53.6, 43.8, 54.9, 56.1, 58.8};
        //double[] Yc_eq = {14.1, 13.7, 17.9, 17.5, 17.1, 21.7, 21.3, 20.8, 25.5, 25, 24.6, 24.2, 29.2, 28.8, 28.4, 28, 33, 32.5, 32.1, 31.7, 36.8, 36.3, 35.9, 35.5, 39.7, 39.3, 38.5, 37.8, 43.5, 43.1, 42.3, 41.5, 47.3, 46.9, 46.1, 45.3, 51.1, 50.6, 49.8, 49, 54.8, 54.4, 53.6, 52.8, 52.8, 57.3, 56.6, 55.8, 65.8, 64.9, 64.1, 63.4, 73.3, 72.4, 71.6, 70.8, 80, 79.2, 78.4, 77.3, 95, 94.2, 93.4, 92.2, 109.4, 108.6, 107.4, 106.2, 146.4, 145.1, 143.9, 141.2};
        double[] Rmin_eq = {7.3, 9.3, 7.2, 11.3, 9.1, 13.3, 9.1, 11.2, 15.4, 17.4, 13.2, 11.1, 19.4, 15.3, 13.1, 17.3, 15.1, 12.9, 19.3, 17.2, 15, 19.2, 17, 21.1, 19, 23.1, 25.1, 21, 27.1, 22.9, 29.2, 25, 27, 20.7, 29.1, 22.7, 31.1, 24.7, 20.3, 35, 26.7, 22.3, 28.8, 39.1, 24.4, 30.8, 26.4, 34.7, 28.4, 30.4, 38.8, 42.8, 34.4, 30.1, 38.5, 34.1, 51, 42.5, 38.2, 42.2, 50.7, 58.6, 50.3, 41.7, 58.3, 49.8, 57.8, 78.4, 57.3, 77.9, 77.5, 76.3};
        double[] Ag_uneq = {141, 184, 188, 218, 225, 234, 246, 286, 302, 307, 352, 356, 378, 416, 447, 476, 526, 552, 565, 602, 625, 627, 656, 716, 737, 746, 817, 858, 865, 938, 955, 978, 1014, 1052, 1137, 1152, 1166, 1202, 1257, 1286, 1336, 1401, 1538, 1551, 1650, 1657, 1698, 1742, 1902, 1956, 2058, 2102, 2156, 2498, 2552, 2562, 2903, 3038, 3400, 3459, 3752, 4056, 4278, 5025, 5976};
        double[] Xc_uneq = {9.8, 10.2, 13, 14.2, 10.6, 16.3, 13.5, 14.7, 13.9, 16.8, 15.1, 14.3, 17.2, 15.5, 17.6, 19.5, 20.7, 22.7, 19.9, 23.9, 21.1, 26, 23.2, 24.4, 20.7, 26.4, 21.9, 24, 28.7, 25.2, 31.9, 27.2, 30.1, 24.8, 29.6, 26, 40.5, 28.1, 32.8, 37, 31, 30.4, 41.5, 33.7, 31.9, 31.2, 38, 52.3, 42.4, 32.7, 44.6, 38.8, 52.3, 39.6, 45.5, 54.1, 69.6, 46.4, 59.9, 70.5, 47.6, 60.8, 71.8, 62, 63.3}; 
        double[] Yc_uneq = {4.9, 5.3, 5.7, 6.9, 5.7, 6.5, 6.2, 7.3, 6.6, 7, 7.7, 6.9, 7.4, 8.1, 7.8, 9.6, 10.8, 10.4, 10, 11.6, 11.2, 11.2, 10.9, 12, 10.8, 11.6, 12, 11.6, 13.9, 12.8, 14.7, 12.4, 17.8, 12.4, 14.8, 13.6, 15.9, 13.2, 15.5, 22.2, 18.7, 15.5, 16.8, 16.3, 19.5, 16.3, 23.1, 15.3, 17.6, 20.3, 27.3, 23.9, 16.1, 24.7, 28.2, 16.9, 20.1, 29, 35.1, 21, 30.2, 36, 22.2, 37.2, 38.4};
        double[] Rmin_uneq = {4.1, 4.1, 5.2, 6.3, 4.1, 6.5, 5.2, 6.3, 5.2, 6.3, 6.3, 5.2, 6.3, 6.3, 6.3, 8.5, 9.6, 9.6, 8.5, 10.7, 9.5, 10.7, 9.6, 10.7, 8.4, 10.7, 9.5, 9.5, 12.8, 10.6, 13.9, 10.6, 15.9, 9.5, 12.8, 10.6, 16.2, 10.6, 13.9, 20.3, 15.9, 12.7, 16.1, 13.8, 15.8, 12.7, 20.2, 16, 16.1, 15.8, 24.5, 20.2, 15.9, 20.1, 24.4, 15.8, 21.4, 24.4, 32.1, 21.3, 24.3, 32.1, 21.2, 32, 31.9};         
       
        double FL = Double.parseDouble(tf31.getText());
        double Lten = Double.parseDouble(tf32.getText());
        double SR = Double.parseDouble(tf33.getText());
        double Fu = Double.parseDouble(tf36.getText());
        double Fy = Double.parseDouble(tf37.getText());
        double ym1 = Double.parseDouble(tf38.getText());
        double ym0 = Double.parseDouble(tf39.getText());
        double ymw = Double.parseDouble(tf35.getText());
        double tt = Double.parseDouble(tf34.getText());
        double L,B,t;
        if(rb38.isSelected()){
          Tenth out = new Tenth();
          out.yeah.append("---------------------------------------------------------------");
          out.yeah.append("\nInputs: ");
          out.yeah.append("\nFactored Load                       "+FL+" kN");
          out.yeah.append("\nLength of Tension Member            "+Lten+" mm");
          out.yeah.append("\nAllowable Slenderness Ratio         "+SR);
          out.yeah.append("\nType of Section                     "+L31.getText());
          out.yeah.append("\nUltimate Stress of Steel            "+Fu+" N/mm^2");
          out.yeah.append("\nYield Stress of Steel               "+Fy+" N/mm^2");
          out.yeah.append("\nThroat Thickness for weld           "+tt+" mm");
          out.yeah.append("\nPartial Safety Factor governed by:          ");
          out.yeah.append("\nUltimate Stress(ym1)                "+ym1);
          out.yeah.append("\nYielding(ym0)                       "+ym0);
          out.yeah.append("\nPartial Safety factor for weld      "+ymw);
          out.yeah.append("\nWeld is distributed on the two sides parallel to axis of the load");
          out.yeah.append("\n---------------------------------------------------------------");
          int idx=0;
          String sec= "";
          double Rmin = 0,ISA=0,Xc=0,Lc = 0,Lnc = 0;      
         if(rb35.isSelected()){
             sec = (String)cb32.getSelectedItem(); 
             idx = cb32.getSelectedIndex(); 
             Rmin = Rmin_eq[idx];
             Xc = Xc_eq[idx];
             ISA = Ag_eq[idx];
          }
          if(rb36.isSelected()){
             sec = (String)cb33.getSelectedItem();
             idx = cb33.getSelectedIndex();
            if(cb31.getSelectedIndex()==1){
                Xc = Xc_uneq[idx];
            }
            if(cb31.getSelectedIndex()==0){
                Xc = Yc_uneq[idx];
            }
             Rmin = Rmin_uneq[idx];
             ISA = Ag_uneq[idx];
          }
          String[] res = sec.split("X");
          //System.out.println("hurray");
          L = Double.parseDouble(res[0]); 
          B = Double.parseDouble(res[1]); 
          t = Double.parseDouble(res[2]);
          if(rb36.isSelected()){
            if(cb31.getSelectedIndex()==1){
                Lnc = B;
                Lc = L;
            }
            if(cb31.getSelectedIndex()==0){
                Lnc = L;
                Lc = B;
            }
          } 
          double Ag = (double)Math.round(((FL*ym0)/Fy)*1000000)/1000;
          out.yeah.append("\nRequired Area of Cross Section area is: "+Ag+" mm^2");
          double sw = (double)Math.round(tt*Fu/(Math.sqrt(3)*ymw))/1000;
          out.yeah.append("\nStrength of weld per mm = (throat thickness)XFu/(root(3)Xymw) = "+sw);
          double tw = 0;
          if(c){
          tw = (double)Math.ceil((double)FL/(2*sw));
          out.yeah.append("\nTotal weld required per ISA angle in mm = Factored Load/(2xStrength of weld per mm)");
          out.yeah.append("\nTotal weld required per ISA angle in mm = "+tw);
          out.yeah.append("\n");          
          }
          else{
          tw = (double)Math.ceil((double)FL/sw);
          out.yeah.append("\nTotal weld required in mm = Factored Load/Strength of weld per mm = " + sw);
          out.yeah.append("\nTotal weld required in mm = "+tw);
          out.yeah.append("\n");
          }
          out.yeah.append("\nSection choosen is ISA "+sec+" with cross sectional area of "+ISA+" mm^2");
          if(c){
           out.yeah.append("\nTotal cross sectional area(combined) = 2x"+ISA+" = ");
           ISA = 2*ISA;
           out.yeah.append(""+ISA+" mm^2");
           }
          out.yeah.append("\nand the centre of gravity is "+Xc+" mm above the base of it's connected leg");
          out.yeah.append("\n");
          if(ISA<Ag){
           out.yeah.append("\nAs we can see,( "+ISA+" < "+Ag+" ), this section is not meeting this requirement, hence this section can't be choosen");  
           out.L10.setText("The chosen section, "+sec+" cannot sustain the given load condition");
          }
          else{
           out.yeah.append("\nMinimum length of weld at the upper side of the angle =");
           out.yeah.append("\nFactored LoadXCentre of Gravity/(Weld per lengthXlength of connected leg)");
           double Iw1 = (double)Math.ceil((double)(FL*Xc)/(sw*Lc));
           double Iw2 = tw - Iw1;
           out.yeah.append("\nMinimum length of weld at the upper side of the angle,Iw1 = "+Iw1+" mm");
           out.yeah.append("\nMinimum length of weld over the lower side of the angle,Iw2 = "+tw+" - "+Iw1+" = "+Iw2+" mm");
           out.yeah.append("\n");
           out.yeah.append("\n");
           out.yeah.append("\n->Gross Section Yielding:");
           double Tdg = (double)Math.round(ISA*Fy/ym0)/1000;
           out.yeah.append("\nTdg = AgxFy/ymf\nTdg = "+Tdg+" kN");
           if(Tdg<FL){
            out.yeah.append("\nAs we can see,( "+FL+" < "+Tdg+" ), this section is not meeting this requirement, hence this section can't be choosen");  
            out.L10.setText("The chosen section, "+sec+" cannot sustain the given load condition");
           }else{
           out.yeah.append("\n");
           out.yeah.append("\n");
           out.yeah.append("\n->Check for net section rupture:");
           double alpha = 0.8;
           double An = (L+B-t)*t;
           double Tdn = (double)Math.round((alpha*An*Fu)/ym1)/1000;
            out.yeah.append("\nAn = "+An+" mm^2");
            out.yeah.append("\nTdn = alpha x An x fu/ym1");
            out.yeah.append("\nTdn = "+Tdn+" kN");
            if(c){
            Tdn = 2*Tdn;
            out.yeah.append("\nTotal Tdn(combined) = 2xTdn = "+Tdn+" kN");
            }
           if(Tdn<FL){
             out.yeah.append("\nAs we can see,( "+Tdn+" < "+FL+" ), this section is not meeting this requirement, hence this section can't be choosen");
             out.L10.setText("The chosen section, "+sec+" cannot sustain the given load condition");
           }else{
            out.yeah.append("\n");
            out.yeah.append("\n");
            out.yeah.append("\n->Block Shear Failure:");
            double Avg = (double)Math.round(tw*2880/272);
            double Avn = Avg;
            double Atg = t*Lc;
            double Atn = Atg;
            out.yeah.append("\nAvg = "+Avg+" mm^2");
            out.yeah.append("\nAvn = "+Avn+" mm^2");
            out.yeah.append("\nAtg = "+Atg+" mm^2");
            out.yeah.append("\nAtn = "+Atn+" mm^2");
            double Tdb1 =  (double)Math.round(0.9*Avn*Fu/(Math.sqrt(3)*ym1) + Atg*Fy/ym0)/1000;
            double Tdb2 =  (double)Math.round(Avg*Fy/(Math.sqrt(3)*ym0) + 0.9*Atn*Fu/ym1)/1000;
            double Tdb = Math.min(Tdb1,Tdb2);
            out.yeah.append("\nTdb1 = 0.9xAvnxFu/(root(3)xym1) + AtgxFy/ym0= "+Tdb1+" kN");
            out.yeah.append("\nTdb2 = AvgxFy/(Math.sqrt(3)xym0) + 0.9xAtnxFu/ym1 = "+Tdb2+" kN");
            out.yeah.append("\nTdb = Min(Tdb1,Tdb2) = "+Tdb+" kN");
            if(c){
            Tdb = 2*Tdb;
            out.yeah.append("\nTotal Tdb(combined) = 2xTdb = "+Tdb+" kN");
            }
            if(Tdb<FL){
            out.yeah.append("\nAs we can see,( "+Tdb+" < "+FL+" ), this section is not meeting this requirement, hence this section can't be choosen");
            out.L10.setText("The chosen section, "+sec+" cannot sustain the given load condition");
                }else{
             out.yeah.append("\n");
             out.yeah.append("\n");
             out.yeah.append("\n->Check for Slenderness Ratio:"); 
             double lambda = (double)Math.round(Lten*1000/Rmin)/1000;
             out.yeah.append("\nlambda = Length of Tension Member/Rmin = "+Lten+"/"+Rmin+" = "+lambda);
             if(lambda>SR){
                 out.yeah.append("\nAs we can see,( "+lambda+" > "+SR+" ), this section is not meeting this requirement, hence this section can't be choosen");
                 out.L10.setText("The chosen section, "+sec+" cannot sustain the given load condition");
                   }else{
                 out.yeah.append("\nAs we can see,( "+lambda+" < "+SR+" ), so OK");
                 out.yeah.append("\nHence, the choosen section is "+sec+" is OK under the given load configuration");
                 out.L10.setText("The chosen section, "+sec+" is OK and can sustain the given load condition");
                  }
                }
              }
            }           
          }
          out.L111.setText(L34.getText());
          out.yeah.setEditable(false);
          out.setVisible(true);
        }
   if(rb37.isSelected()){
          Tenth out = new Tenth();
          out.yeah.append("---------------------------------------------------------------");
          out.yeah.append("\nInputs: ");
          out.yeah.append("\nFactored Load                       "+FL+" kN");
          out.yeah.append("\nLength of Tension Member            "+Lten+" mm");
          out.yeah.append("\nAllowable Slenderness Ratio         "+SR);
          out.yeah.append("\nType of Section                     "+L31.getText());
          out.yeah.append("\nUltimate Stress of Steel            "+Fu+" N/mm^2");
          out.yeah.append("\nYield Stress of Steel               "+Fy+" N/mm^2");
          out.yeah.append("\nThroat Thickness for weld           "+tt+" mm");
          out.yeah.append("\nPartial Safety Factor governed by:          ");
          out.yeah.append("\nUltimate Stress(ym1)                "+ym1);
          out.yeah.append("\nYielding(ym0)                       "+ym0);
          out.yeah.append("\nPartial Safety factor for weld      "+ymw);
          out.yeah.append("\nWeld is distributed on the two sides parallel to axis of the load");
          out.yeah.append("\n---------------------------------------------------------------");
          int idx=0;
          int k = 1;
          double lambda = 10000;
          double tw = 0; 
          double Ag = (double)Math.round(((FL*ym0)/Fy)*1000000)/1000;
          out.yeah.append("\nRequired Area of Cross Section area is: "+Ag+" mm^2");
          double sw = (double)Math.round(tt*Fu/(Math.sqrt(3)*ymw))/1000;
          out.yeah.append("\nStrength of weld per mm = (throat thickness)XFu/(root(3)Xymw) = "+sw);
          if(c){
          tw = (double)Math.ceil((double)FL/(2*sw));
          out.yeah.append("\nTotal weld required per ISA angle in mm = Factored Load/(2xStrength of weld per mm)");
          out.yeah.append("\nTotal weld required per ISA angle in mm = "+tw);
          out.yeah.append("\n");          
          }
          else{
          tw = (double)Math.ceil((double)FL/sw);
          out.yeah.append("\nTotal weld required in mm = Factored Load/Strength of weld per mm = " + sw);
          out.yeah.append("\nTotal weld required in mm = "+tw);
          out.yeah.append("\n");
          }
         while(lambda>SR){
          String sec= "";
          double Rmin = 0,ISA=0,Xc=0,Lc = 0,Lnc = 0;      
         if(rb35.isSelected()){
           if(idx==72){
              out.L10.setText("There exist no such "+L31.getText()+" section that can sustain the given load condition");
              break;
            }             
             cb32.setSelectedIndex(idx); 
             sec = (String)cb32.getSelectedItem(); 
             Rmin = Rmin_eq[idx];
             Xc = Xc_eq[idx];
             ISA = Ag_eq[idx];
          }
          if(rb36.isSelected()){ 
              if(idx==65){
              out.L10.setText("There exist no such "+L31.getText()+" section that can sustain the given load condition");
              break;
              }
             cb33.setSelectedIndex(idx);
             sec = (String)cb33.getSelectedItem();
            if(cb31.getSelectedIndex()==1){
                Xc = Xc_uneq[idx];
            }
            if(cb31.getSelectedIndex()==0){
                Xc = Yc_uneq[idx];
            }
             Rmin = Rmin_uneq[idx];
             ISA = Ag_uneq[idx];
          }
          double ISA1 =ISA;
          if(c){
          ISA = 2*ISA;
          }
          if(ISA<Ag){
          idx++;
          continue;
          }
          String[] res = sec.split("X");
          //System.out.println("hurray");
          L = Double.parseDouble(res[0]); 
          B = Double.parseDouble(res[1]); 
          t = Double.parseDouble(res[2]);
          if(rb35.isSelected()){
            Lc = L;
          }
          if(rb36.isSelected()){
            if(cb31.getSelectedIndex()==1){
                Lnc = B;
                Lc = L;
            }
            if(cb31.getSelectedIndex()==0){
                Lnc = L;
                Lc = B;
            }
          }
          
          out.yeah.append("\n");
          out.yeah.append("\n");
          out.yeah.append("\nTest Case "+k+":");
              k++;           
          out.yeah.append("\nSection choosen is ISA "+sec+" with cross sectional area of "+ISA1+" mm^2");
          out.yeah.append("\nand the centre of gravity is "+Xc+" mm above the base of it's connected leg.");
          if(c){
           out.yeah.append("\nTotal cross sectional area(combined) = 2x"+ISA1+" = ");
           out.yeah.append(""+ISA+" mm^2");
           }
          out.yeah.append("\n");
          out.yeah.append("\nMinimum length of weld at the upper side of the angle =");
           out.yeah.append("\nFactored LoadXCentre of Gravity/(Weld per lengthXlength of connected leg) = ");
           double Iw1 = (double)Math.ceil((double)(FL*Xc)/(sw*Lc));
           double Iw2 = tw - Iw1;
           out.yeah.append("\nMinimum length of weld at the upper side of the angle,Iw1 = "+Iw1+" mm");
           out.yeah.append("\nMinimum length of weld over the lower side of the angle,Iw2 = "+tw+" - "+Iw1+" = "+Iw2+" mm");
           out.yeah.append("\n");
           out.yeah.append("\n");           
           out.yeah.append("\n->Gross Section Yielding:");
           double Tdg = (double)Math.round(ISA*Fy/ym0)/1000;
           out.yeah.append("\nTdg = AgxFy/ymf\nTdg = "+Tdg+" kN");
          if(Tdg<FL){
            out.yeah.append("\nAs we can see,( "+FL+" < "+Tdg+" ), this section is not meeting this requirement, Let's, try another section"); 
            idx++;
            continue;
           }else{
           out.yeah.append("\n");
           out.yeah.append("\n");
           out.yeah.append("\n->Check for net section rupture:");
           double alpha = 0.8;
           double An = (L+B-t)*t;
           double Tdn = (double)Math.round((alpha*An*Fu)/ym1)/1000;
            out.yeah.append("\nalpha = "+alpha+" calculated from the number of bolts");
            out.yeah.append("\nAn = "+An+" mm^2");
            out.yeah.append("\nTdn = alpha x An x fu/ym1");
            out.yeah.append("\nTdn = "+Tdn+" kN");
            if(c){
            Tdn = 2*Tdn;
            out.yeah.append("\nTotal Tdn(combined) = 2xTdn = "+Tdn+" kN");
            }
           if(Tdn<FL){
             out.yeah.append("\nAs we can see,( "+Tdn+" < "+FL+" ), this section is not meeting this requirement, Let's, try another section");
             idx++;
            continue;
           }else{
            out.yeah.append("\n");
            out.yeah.append("\n");
            out.yeah.append("\n->Block Shear Failure:");
            double Avg = (double)Math.round(tw*2880/272);
            double Avn = Avg;
            double Atg = t*Lc;
            double Atn = Atg;
            out.yeah.append("\nAvg = "+Avg+" mm^2");
            out.yeah.append("\nAvn = "+Avn+" mm^2");
            out.yeah.append("\nAtg = "+Atg+" mm^2");
            out.yeah.append("\nAtn = "+Atn+" mm^2");
            double Tdb1 =  (double)Math.round(0.9*Avn*Fu/(Math.sqrt(3)*ym1) + Atg*Fy/ym0)/1000;
            double Tdb2 =  (double)Math.round(Avg*Fy/(Math.sqrt(3)*ym0) + 0.9*Atn*Fu/ym1)/1000;
            double Tdb = Math.min(Tdb1,Tdb2);
            out.yeah.append("\nTdb1 = 0.9xAvnxFu/(root(3)xym1) + AtgxFy/ym0= "+Tdb1+" kN");
            out.yeah.append("\nTdb2 = AvgxFy/(Math.sqrt(3)xym0) + 0.9xAtnxFu/ym1 = "+Tdb2+" kN");
            out.yeah.append("\nTdb = Min(Tdb1,Tdb2) = "+Tdb+" kN");
            if(c){
            Tdn = 2*Tdn;
            out.yeah.append("\nTotal Tdn(combined) = 2xTdn = "+Tdn+" kN");
            }
            if(Tdb<FL){
            out.yeah.append("\nAs we can see,( "+Tdb+" < "+FL+" ), this section is not meeting this requirement, Let's, try another section");
            idx++;
           continue;
                }else{
             out.yeah.append("\n");
             out.yeah.append("\n");
             out.yeah.append("\n->Check for Slenderness Ratio:"); 
             lambda = (double)Math.round(Lten*1000/Rmin)/1000;
             out.yeah.append("\nlambda = Length of Tension Member/Rvv = "+Lten+"/"+Rmin+" = "+lambda);
             if(lambda>SR){
                 out.yeah.append("\nAs we can see,( "+lambda+" > "+SR+" ), this section is not meeting this requirement, Let's, try another section");
                 idx++;
                 continue;
                   }else{
                 out.yeah.append("\nAs we can see,( "+lambda+" < "+SR+" ), so OK");
                 out.yeah.append("\nHence, the choosen section is "+sec+" is OK and the OPTIMUM ONE under the given load configuration");
                 out.L10.setText("The choosen section is "+sec+", is OK and the OPTIMUM ONE under the given load configuration");
                break;
                  }
                }
              }
            }         
         }
         out.L111.setText(L34.getText());
          out.yeah.setEditable(false);
          out.setVisible(true);       
      }
      // TODO add your handling code here:
    }//GEN-LAST:event_b33ActionPerformed

    private void tf33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf33ActionPerformed

    private void cb31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb31ActionPerformed
    L31.setText("Unequal with "+ cb31.getSelectedItem());
        // TODO add your handling code here:
    }//GEN-LAST:event_cb31ActionPerformed

    private void tf35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf35ActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_tf35ActionPerformed

    private void b32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b32ActionPerformed
        this.toBack();
        this.setVisible(false);
        new First().toFront();
        new First().setState(java.awt.Frame.NORMAL); 
        // TODO add your handling code here:
    }//GEN-LAST:event_b32ActionPerformed

    private void chb31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb31ActionPerformed
     if(chb31.isSelected()){
         tf36.setText("410");
         tf36.setEnabled(false);
         tf37.setText("250");
         tf37.setEnabled(false);
     }
     if(!chb31.isSelected()){
         tf36.setEnabled(true);
         tf37.setEnabled(true);
     }
    }//GEN-LAST:event_chb31ActionPerformed

    private void tf37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf37ActionPerformed

    private void tf39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf39ActionPerformed

    private void tf36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf36ActionPerformed

    private void rb35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb35ActionPerformed
    if(rb35.isSelected()){
      cb31.setEnabled(false);
      cb33.setEnabled(false);
      cb32.setEnabled(true);
     } 
    if(rb37.isSelected()){
      cb33.setEnabled(false);
      cb32.setEnabled(false);
     }
    L31.setText("Equal");
        // TODO add your handling code here:
    }//GEN-LAST:event_rb35ActionPerformed

    private void rb37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb37ActionPerformed
     if(rb37.isSelected()){
      cb33.setEnabled(false);
      cb32.setEnabled(false);
     }
        // TODO add your handling code here:
    }//GEN-LAST:event_rb37ActionPerformed

    private void rb38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb38ActionPerformed
    if(rb38.isSelected()){
         if(rb35.isSelected())
         {
      cb31.setEnabled(false);
      cb33.setEnabled(false);
      cb32.setEnabled(true);
         }else 
      if(rb36.isSelected())
         {
      cb31.setEnabled(true);
      cb33.setEnabled(true);
      cb32.setEnabled(false);
         }else 
      {
        cb31.setEnabled(true);
      cb33.setEnabled(true);
      cb32.setEnabled(true);
      }
      
     } 
        // TODO add your handling code here:
    }//GEN-LAST:event_rb38ActionPerformed

    private void rb36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb36ActionPerformed
    if(rb36.isSelected()){
      cb31.setEnabled(true);
      cb33.setEnabled(true);
      cb32.setEnabled(false);
     } 
    if(rb37.isSelected()){
      cb33.setEnabled(false);
      cb32.setEnabled(false);
     }
        // TODO add your handling code here:
    }//GEN-LAST:event_rb36ActionPerformed

    private void cb32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb32ActionPerformed
        L33.setText("Choosen section : ");
        L32.setText("" + cb32.getSelectedItem());     
        //L31.setText("Choosen section : " + cb32.getSelectedItem());  
        // TODO add your handling code here:
    }//GEN-LAST:event_cb32ActionPerformed

    private void cb33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb33ActionPerformed
       L33.setText("Choosen section : ");
       L32.setText("" + cb33.getSelectedItem());
        // TODO add your handling code here:
    }//GEN-LAST:event_cb33ActionPerformed

    private void rb33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb33ActionPerformed
    if(rb33.isSelected()){
    tf35.setText("1.10");
    tf35.setEnabled(false);
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_rb33ActionPerformed

    private void rb34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb34ActionPerformed
    if(rb34.isSelected()){
    tf35.setText("1.25");
    tf35.setEnabled(false);
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_rb34ActionPerformed

    private void chb32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb32ActionPerformed
    if(chb32.isSelected()){
         tf38.setText("1.25");
         tf38.setEnabled(false);
         tf39.setText("1.1");
         tf39.setEnabled(false);
      }   
       if(!chb32.isSelected()){
         tf38.setEnabled(true);
         tf39.setEnabled(true);
      }    
        // TODO add your handling code here:
    }//GEN-LAST:event_chb32ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Third_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Third_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Third_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Third_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Third_().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L31;
    private javax.swing.JLabel L32;
    private javax.swing.JLabel L33;
    public static javax.swing.JLabel L34;
    private javax.swing.JPanel P22;
    private javax.swing.JButton b32;
    public static javax.swing.JButton b33;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JComboBox<String> cb31;
    private javax.swing.JComboBox<String> cb32;
    private javax.swing.JComboBox<String> cb33;
    private javax.swing.JCheckBox chb31;
    private javax.swing.JCheckBox chb32;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton rb33;
    private javax.swing.JRadioButton rb34;
    private javax.swing.JRadioButton rb35;
    private javax.swing.JRadioButton rb36;
    public static javax.swing.JRadioButton rb37;
    public static javax.swing.JRadioButton rb38;
    private javax.swing.JTextField tf31;
    private javax.swing.JTextField tf32;
    private javax.swing.JTextField tf33;
    private javax.swing.JTextField tf34;
    private javax.swing.JTextField tf35;
    private javax.swing.JTextField tf36;
    private javax.swing.JTextField tf37;
    private javax.swing.JTextField tf38;
    private javax.swing.JTextField tf39;
    // End of variables declaration//GEN-END:variables
}
